# Created at 2018-10-05T12:13:32.031
java.lang.reflect.InvocationTargetException

# Created at 2018-10-05T12:13:32.050
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

# Created at 2018-10-05T12:13:32.053
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

# Created at 2018-10-05T12:13:32.053
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

# Created at 2018-10-05T12:13:32.070
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)

# Created at 2018-10-05T12:13:32.075
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:510)

# Created at 2018-10-05T12:13:32.075
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:522)

# Created at 2018-10-05T12:13:32.093
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.

# Created at 2018-10-05T12:13:32.098
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)

# Created at 2018-10-05T12:13:32.106
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)

# Created at 2018-10-05T12:13:32.126
	at org.jacoco.agent.rt.internal_8ff85ea.PreMain.createRuntime(PreMain.java:55)

# Created at 2018-10-05T12:13:32.132
	at org.jacoco.agent.rt.internal_8ff85ea.PreMain.premain(PreMain.java:47)

# Created at 2018-10-05T12:13:32.150
	... 6 more

# Created at 2018-10-05T12:13:32.174
Caused by: java.lang.NoSuchFieldException: $jacocoAccess

# Created at 2018-10-05T12:13:32.178
	at java.base/java.lang.Class.getField(Class.java:1958)

# Created at 2018-10-05T12:13:32.192
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)

# Created at 2018-10-05T12:13:32.203
	... 9 more

# Created at 2018-10-05T12:13:32.214
Exception in thread "main" 

